#!/bin/bash

set -e

file=mmc.img
mnt=/mnt/x
fat=/mnt/y
dstdir=$fat/extlinux

vmlinux=vmlinuz-5.3.7-301.fc31.armv7hl
initrd=initramfs-5.3.7-301.fc31.armv7hl.img
dtb=dtb-5.3.7-301.fc31.armv7hl/sandbox.dtb

old() {
	mkfs.vfat $file
	sudo mount -o loop $file $mnt
	#sudo cp /tmp/b/efi-x86_payload64/u-boot-payload.efi /mnt/x
	#sudo cp /tmp/efi64/startup.nsh  $mnt
	#sudo cp /tmp/efi64/vmlinuz $mnt
	echo >>/tmp/extlinux.conf <<EOF
ui menu.c32

menu autoboot Arch Boot. Automatic boot in # second{,s}. Press a key for options.
menu title Arch Boot Options.
menu hidden

timeout 50

default Arch

label Arch
    kernel /zImage
    append root=/dev/mmcblk0p2 rw rootfstype=ext4 rootwait consoleblank=0 no_console_suspend=1 console=ttymxc0,115200n8
    fdtdir /dtbs
    initrd /initramfs-linux.img
EOF
	sudo cp /tmp/extlinux.conf $mnt
	ls $mnt
	sudo umount $mnt
}


fat_setup() {
	echo 'type=c' | sudo sfdisk $file
	#sudo kpartx -a $file
	loop=$(sudo losetup --show -f -P $file)
	echo "Mounted to $loop"
	fatpart="${loop}p1"
 	sudo mkfs.vfat $fatpart
	sudo mount -o loop ${fatpart} $fat
}


fat_finish() {
	sudo mkdir -p $dstdir
	sudo cp /tmp/extlinux.conf $dstdir

	echo "vmlinux" | gzip >/tmp/inf
	mkimage -f auto -d /tmp/inf /tmp/$vmlinux

	sudo cp /tmp/$vmlinux $fat

	echo "initd" >/tmp/$initrd
	sudo cp /tmp/$initrd $fat

	dtb_dir="$(dirname /tmp/$dtb)"
	mkdir -p $dtb_dir
	echo "/dts-v1/; / {};" | dtc >/tmp/$dtb
	sudo cp -r $dtb_dir $fat

	ls $dstdir

	sudo umount $fat

	losetup -d $loop
}


new() {
	fat_setup
	cat >/tmp/extlinux.conf << EOF
ui menu.c32

menu autoboot Arch Boot. Automatic boot in # second{,s}. Press a key for options.
menu title Arch Boot Options.
menu hidden

timeout 50

default Arch

label Arch
    kernel /zImage
    append root=/dev/mmcblk0p2 rw rootfstype=ext4 rootwait consoleblank=0 no_console_suspend=1 console=ttymxc0,115200n8
    fdtdir /dtbs
    initrd /initramfs-linux.img
EOF
	fat_finish
}


fedora31() {
	fat_setup
	cat >/tmp/extlinux.conf << EOF
# extlinux.conf generated by appliance-creator
ui menu.c32
menu autoboot Welcome to Fedora-Workstation-armhfp-31-1.9. Automatic boot in # second{,s}. Press a key for options.
menu title Fedora-Workstation-armhfp-31-1.9 Boot Options.
menu hidden
timeout 20
totaltimeout 600

label Fedora-Workstation-armhfp-31-1.9 (5.3.7-301.fc31.armv7hl)
	kernel /$vmlinux
	append ro root=UUID=9732b35b-4cd5-458b-9b91-80f7047e0b8a rhgb quiet LANG=en_US.UTF-8 cma=192MB cma=256MB
	fdtdir /dtb-5.3.7-301.fc31.armv7hl/
	initrd /$initrd
EOF
	fat_finish
}

# Remove old devices
for dev in $(losetup |grep $file | awk '{print $1}'); do
	echo "Remove $dev"
	losetup -d $dev
done

qemu-img create $file 20M
#old
#new
fedora31
