# SPDX-License-Identifier: GPL-2.0+
#
# Copyright 2018 Google LLC
#

obj-y += vboot-flag-uclass.o
obj-$(CONFIG_CROS_FLAG_CONST) += flag_const.o
obj-$(CONFIG_CROS_FLAG_GPIO) += flag_gpio.o
obj-$(CONFIG_CROS_FLAG_KEY) += flag_key.o
obj-$(CONFIG_CROS_FLAG_SYSINFO) += flag_sysinfo.o
