# SPDX-License-Identifier:	GPL-2.0+
#
# Copyright 2018 Google LLC
#

obj-y += fwstore-uclass.o
obj-y += fwstore_reader.o
obj-$(CONFIG_$(SPL_TPL_)FWSTORE_MMC) += fwstore_mmc.o
obj-$(CONFIG_$(SPL_TPL_)FWSTORE_SPI_FLASH) += fwstore_spi.o
