/* SPDX-License-Identifier: GPL-2.0+ */
/*
 * Chromium OS common definitions for bootstage and TPM
 *
 * Copyright 2018 Google LLC
 */

#ifndef __CROS_COMMON_H
#define __CROS_COMMON_H

enum {
	BOOTSTAGE_VBOOT_FIRST = BOOTSTAGE_ID_USER,

	BOOTSTAGE_VBOOT_START = BOOTSTAGE_VBOOT_FIRST,
	BOOTSTAGE_VBOOT_START_TPMINIT,
	BOOTSTAGE_VBOOT_END_TPMINIT,
	BOOTSTAGE_VBOOT_START_VERIFY_SLOT,
	BOOTSTAGE_VBOOT_END_VERIFY_SLOT,
	BOOTSTAGE_VBOOT_START_HASH_BODY,
	BOOTSTAGE_VBOOT_END_HASH_BODY,
	BOOTSTAGE_VBOOT_DONE_HASHING,
	BOOTSTAGE_VBOOT_START_TPMPCR,
	BOOTSTAGE_VBOOT_END_TPMPCR,
	BOOTSTAGE_VBOOT_START_TPMLOCK,
	BOOTSTAGE_VBOOT_END_TPMLOCK,
	BOOTSTAMP_VBOOT_EC_DONE,
	BOOTSTAGE_VBOOT_END,
	BOOTSTAGE_VBOOT_DONE,

	/*
	 * Each vboot stage has a bootstage record starting at
	 * BOOTSTAGE_VBOOT_FIRST.
	 */
	BOOTSTAGE_ACCUM_VBOOT_BOOT_DEVICE_INFO,
	BOOTSTAGE_ACCUM_VBOOT_BOOT_DEVICE_READ,
	BOOTSTAGE_ACCUM_VBOOT_FIRMWARE_READ,

	BOOTSTAGE_VBOOT_LAST,
};

/* extra flags for enum tpm_return_code used by vboot */
enum {
	TPM_E_ALREADY_INITIALISED	= 0x5000,
	TPM_E_INTERNAL_INCONSISTENCY,
	TPM_E_MUST_REBOOT,
	TPM_E_CORRUPTED_STATE,
	TPM_E_COMMUNICATION_ERROR,
	TPM_E_RESPONSE_TOO_LARGE,
	TPM_E_NO_DEVICE,
	TPM_E_INPUT_TOO_SMALL,
	TPM_E_WRITE_FAILURE,
	TPM_E_READ_EMPTY,
	TPM_E_READ_FAILURE,
	TPM_E_NV_DEFINED,
};

#endif /* __CROS_COMMON_H */
