# SPDX-License-Identifier:	GPL-2.0+
#
# Copyright 2018 Google LLC
#

obj-$(CONFIG_CHROMEOS) += cmd/
obj-$(CONFIG_CHROMEOS) += crypto/
obj-$(CONFIG_CROS_FLAG) += flag/
obj-$(CONFIG_CHROMEOS) += fwstore/
obj-$(CONFIG_CHROMEOS) += lib/
obj-$(CONFIG_CHROMEOS) += nvdata/
obj-$(CONFIG_CHROMEOS) += stage/
obj-$(CONFIG_CHROMEOS) += vboot/
obj-$(CONFIG_SANDBOX) += soc/sandbox/
