# SPDX-License-Identifier:	GPL-2.0+
#
# Copyright 2018 Google LLC
#

ifndef CONFIG_SPL_BUILD
obj-y += cmd/
endif
obj-y += crypto/
obj-$(CONFIG_CROS_FLAG) += flag/
obj-y += fwstore/
obj-y += lib/
obj-y += nvdata/
obj-y += stage/
obj-y += vboot/
obj-$(CONFIG_SANDBOX) += soc/sandbox/
